- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
- name: pull image
    docker_image:
   name: nginx
#     name: elastisearch
#    name: logstash
#    name: kibana
#    name: filebeat
#    state: latest
